language: python

dist: bionic

# https://devguide.python.org/#branchstatus
python:
  - "3.6"
  - "3.7"

install:
  - sudo apt-get install -y - npm
  - sudo npm install -g markdownlint-cli
  - pip install flake8

script:
  - flake8 emissionsapi
  - markdownlint .
